/* Database schema to keep the structure of entire database. */
-- CREATE TABLE animals (
--     name varchar(100)
-- );

CREATE DATABASE vet_clinic;

CREATE TABLE animals (id integer GENERATED BY DEFAULT AS IDENTITY, name char(50), date_of_birth date, escape_attempts int, neutered boolean, weight_kg decimal(10,2), PRIMARY KEY (id));

ALTER TABLE animals ADD COLUMN species VARCHAR(50);

CREATE TABLE owners (id integer GENERATED BY DEFAULT AS IDENTITY, full_name VARCHAR(255), age integer, PRIMARY KEY (id));

CREATE TABLE species (id integer GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(50), PRIMARY KEY (id));

ALTER TABLE animals ADD COLUMN species_id integer, ADD CONSTRAINT fk_species FOREIGN KEY (species_id) REFERENCES species(id);

ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD COLUMN species_id integer, ADD CONSTRAINT fk_species FOREIGN KEY (species_id) REFERENCES species(id);